version: "3.1" 
services:
  api:
    container_name: nestjs_graphql_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes: 
      - .:/home/api
      - /home/api/node_modules
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    container_name: nest_graphql_postgres
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432